---
galaxy_info:
  author: Sébastien Han
  description: Installs Ceph Mirror Agent
  license: Apache
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
        - trusty
    - name: EL
      versions:
        - 7
  categories:
    - system
dependencies:
  - { role: ceph.ceph-common, when: not rbd_mirror_containerized_deployment }
  - { role: ceph.ceph-docker-common, when: rbd_mirror_containerized_deployment }
