---
- name: create ganesha conf directory
  file:
    path: /etc/ganesha
    state: directory
    owner: root
    group: root
    mode: 0644

- name: create the nfs rgw user
  docker:
    image: "{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
    name: ceph-rgw-user-{{ ansible_hostname }}
    hostname: "{{ ansible_hostname }}"
    expose: "{{ ceph_rgw_civetweb_port }}"
    ports: "{{ ceph_rgw_civetweb_port }}:{{ ceph_rgw_civetweb_port }}"
    state: running
    env: "CEPH_DAEMON=RGW_USER,RGW_USERNAME={{ ceph_nfs_rgw_user }},RGW_USER_ACCESS_KEY={{ ceph_nfs_rgw_access_key }},RGW_USER_SECRET_KEY={{ ceph_nfs_rgw_secret_key }}"
    volumes: "/var/lib/ceph:/var/lib/ceph,/etc/ceph:/etc/ceph"
  when: nfs_obj_gw

- name: get user create output
  command: docker logs ceph-rgw-user-{{ ansible_hostname }}
  always_run: true
  register: rgwuser

- name: generate ganesha configuration file
  action: config_template
  args:
    src: "{{ playbook_dir }}/roles/ceph-common/templates/ganesha.conf.j2"
    dest: /etc/ganesha/ganesha.conf
    owner: "root"
    group: "root"
    mode: "0644"
    config_overrides: "{{ ganesha_conf_overrides }}"
    config_type: ini
