---
- name: create bootstrap directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bootstrap_dirs_owner }}"
    group: "{{ bootstrap_dirs_group }}"
    mode: "0755"
  with_items:
    - /etc/ceph/
    - /var/lib/ceph/
    - /var/lib/ceph/radosgw

- name: create ganesha directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - /etc/ganesha/
    - /var/lib/nfs/ganesha
    - /var/run/ganesha
