---
- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-nfs.service.j2"
    dest: /etc/systemd/system/ceph-nfs@.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: enable systemd unit file for nfs instance
  shell: systemctl enable ceph-nfs@{{ ansible_hostname }}.service
  failed_when: false
  changed_when: false

- name: reload systemd unit files
  shell: systemctl daemon-reload
  changed_when: false
  failed_when: false

- name: systemd start nfs container
  service:
    name: ceph-nfs@{{ ansible_hostname }}
    state: started
    enabled: yes
  changed_when: false

- name: wait for ceph.conf exists
  wait_for:
      path: "/etc/ceph/{{ cluster }}.conf"
  when: is_atomic

