---
- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: started
    enabled: yes
  changed_when: false

# NOTE: This patch only affects Kraken. This fixes a bug when the monitor service
# does not start automatically after a reboot. Fix proposed upstream: ceph/ceph#14226
- name: enable the ceph-mon.target service
  systemd:
    name: ceph-mon.target
    enabled: yes
    masked: no
  changed_when: false
