---
- include: pre_requisite.yml
  when: not rbd_mirror_containerized_deployment

- include: start_rbd_mirror.yml
  when: not rbd_mirror_containerized_deployment

- include: configure_mirroring.yml
  when:
    - ceph_rbd_mirror_configure
    - not rbd_mirror_containerized_deployment

- include: ./docker/main.yml
  when: rbd_mirror_containerized_deployment
